
CREATE DATABASE EVENTSv1
go

USE EVENTSv1
go

CREATE TABLE [OBJECT]
( 
	[PassO]            	INT IDENTITY NOT NULL,
	[Name]           	VARCHAR(100)  NOT NULL 
)
go

ALTER TABLE [OBJECT]
	ADD CONSTRAINT [XPKOBJECT] PRIMARY KEY  CLUSTERED ([PassO] ASC)
go

CREATE TABLE [SECTOR]
( 
	[PassS]            	INT  IDENTITY NOT NULL,
	[Designator]          	VARCHAR(50) NOT NULL,
	[FactorS]         	DECIMAL(10,2) NOT NULL, 
	[RowNum]      	INT NOT NULL, 
	[PassO]            	INT NOT NULL 
)
go

ALTER TABLE [SECTOR]
	ADD CONSTRAINT [XPKSECTOR] PRIMARY KEY  CLUSTERED ([PassS] ASC)
go

CREATE TABLE [ROW]
( 
	[PassR]            	INT IDENTITY NOT NULL,
	[Number]				INT NOT NULL,
	[FactorR]          	DECIMAL(10,2) NOT NULL, 
	[ChairNumber]      	INT NOT NULL, 
	[PassS]             	INT NOT NULL 
)
go

ALTER TABLE [ROW]
	ADD CONSTRAINT [XPKROW] PRIMARY KEY  CLUSTERED ([PassR] ASC)
go



CREATE TABLE [EVENT]
( 
	[PassE]              INT  IDENTITY  NOT NULL,
	[Name]             VARCHAR(50)  NOT NULL,
	[Description]           	VARCHAR(300),
	[Date]             DATE NOT NULL,
	[BasePrice]       DECIMAL(10,2) NOT NULL,
	[RestTicketsNum]  INT
)
go

ALTER TABLE [EVENT]
	ADD CONSTRAINT [XPKEVENT] PRIMARY KEY  CLUSTERED ([PassE] ASC)
go


CREATE TABLE [EVENT_CANCELED]
( 
	[PassE]              INT NOT NULL ,
	[Reason]            VARCHAR(100)  NOT NULL ,
	[Damage]           	DECIMAL(10,2)
)
go

ALTER TABLE [EVENT_CANCELED]
	ADD CONSTRAINT [XPKEVENT_CANCELED] PRIMARY KEY  CLUSTERED ([PassE] ASC)
go

CREATE TABLE [TICKET]
( 
	[PassT]            	INT IDENTITY NOT NULL ,
	[ChairNum]         INT  NOT NULL, 
	[OfficialPrice]      DECIMAL(10,2)  NOT NULL,
	[Status]           	CHAR(1) NOT NULL,
	[PassR]              INT  NOT NULL
)
go

ALTER TABLE [TICKET]
	ADD CONSTRAINT [XPKTICKET] PRIMARY KEY  CLUSTERED ([PassT] ASC)
go

CREATE TABLE [BUYER]
( 
	[PassB]              INT IDENTITY NOT NULL ,
	[Name]              	VARCHAR(50) NOT NULL
)
go

ALTER TABLE [BUYER]
	ADD CONSTRAINT [XPKBUYER] PRIMARY KEY  CLUSTERED ([PassB] ASC)
go

CREATE TABLE [BOUGHT]
( 
	[PassT]              INT NOT NULL,
	[PassB]              INT NOT NULL,
	[Price]           	DECIMAL(10,2) NOT NULL 
)
go

ALTER TABLE [BOUGHT]
	ADD CONSTRAINT [XPKBOUGHT] PRIMARY KEY  CLUSTERED ([PassT] ASC)
go

CREATE TABLE [VALID]
( 
	[PassT]           	INT NOT NULL,
	[PassE]           	INT NOT NULL
)
go

ALTER TABLE [VALID]
	ADD CONSTRAINT [XPKVALID] PRIMARY KEY  CLUSTERED ([PassT] ASC)
go


CREATE TABLE [DISCOUNT]
( 
	[TicketsNumber]      INT NOT NULL,
	[Discount]           	DECIMAL(10,2)  NOT NULL
)
go

ALTER TABLE [DISCOUNT]
	ADD CONSTRAINT [XPKDISCOUNT] PRIMARY KEY  CLUSTERED ([TicketsNumber] ASC)
go


ALTER TABLE [SECTOR]
	ADD CONSTRAINT [R_1] FOREIGN KEY ([PassO]) REFERENCES [OBJECT]([PassO])
		ON DELETE CASCADE
		ON UPDATE CASCADE
go


ALTER TABLE [ROW]
	ADD CONSTRAINT [R_2] FOREIGN KEY ([PassS]) REFERENCES [SECTOR]([PassS])
		ON DELETE CASCADE
		ON UPDATE CASCADE
go


ALTER TABLE [EVENT_CANCELED]
	ADD CONSTRAINT [R_3] FOREIGN KEY ([PassE]) REFERENCES [EVENT]([PassE])
		ON DELETE CASCADE
		ON UPDATE CASCADE
go

ALTER TABLE [TICKET]
	ADD CONSTRAINT [R_4] FOREIGN KEY ([PassR]) REFERENCES [ROW]([PassR])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [BOUGHT]
	ADD CONSTRAINT [R_7] FOREIGN KEY ([PassT]) REFERENCES [TICKET]([PassT])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [BOUGHT]
	ADD CONSTRAINT [R_8] FOREIGN KEY ([PassB]) REFERENCES [BUYER]([PassB])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go


ALTER TABLE [VALID]
	ADD CONSTRAINT [R_9] FOREIGN KEY ([PassT]) REFERENCES [TICKET]([PassT])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

ALTER TABLE [VALID]
	ADD CONSTRAINT [R_10] FOREIGN KEY ([PassE]) REFERENCES [EVENT]([PassE])
		ON DELETE NO ACTION
		ON UPDATE NO ACTION
go

